M48
; DRILL file {KiCad (6.0.10-0)} date Tuesday, February 14, 2023 at 01:22:49 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-14T13:22:49-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X6.3213Y-4.8
X6.4Y-4.8
T2
X4.7031Y-2.7
X4.9031Y-2.7
T0
M30
